name: TimTheEnchanter
main: nu.baxter.enchant.Tim
version: 1.4
website: http://joe.to
author: mbaxter
description: There are some who call me... Tim?
commands:
  enchant:
    usage: |
            /enchant enchantment level
            /enchant all
permissions:
  enchanter.enchant:
    default: op